VacSys/urls.py
from django.contrib import admin
from django.urls import path, include

import vaccine.views

app_name = 'mainapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vaccine.urls', namespace='vaccine')),

]

vaccine/urls.py
from django.urls import path

from .views import MemberListView, MemberDetailView, MemberDeleteView, FirstDoseView, SecondDoseView, DoseDoneView, LandingPageView, HomePage, DateDetails, Verify, CheckDate
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'vaccine'


urlpatterns = [

    path('', HomePage.as_view(), name='index'),
    path('check-date', CheckDate.as_view(), name='check-dates'),
    path('check-date/<pk>', DateDetails.as_view(), name='date-details'),

    path('verify', Verify.as_view(), name='verify'),
    path('login', LoginView.as_view(), name='login'),
    path('dashboard/logout', LogoutView.as_view(), name='logout'),

    path('dashboard/', MemberListView.as_view(), name='dashboard'),
    path('dashboard/first_dose', FirstDoseView.as_view(), name='first-dose'),
    path('dashboard/second_dose', SecondDoseView.as_view(), name='second-dose'),
    path('dashboard/complete_dose', DoseDoneView.as_view(), name='complete_dose'),
    path('dashboard/member/<pk>', MemberDetailView.as_view(), name='member-details'),
    path('dashboard/member/<pk>/delete', MemberDeleteView.as_view(), name='member-delete'),

]

urlpatterns += staticfiles_urlpatterns()

vaccine/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    USER_TYPE_CHOICES = (
        (1, 'Admin'),
        (2, 'Staff'),
    )
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1)


class Member(models.Model):
    nid = models.IntegerField(primary_key=True)
    first_name = models.TextField(max_length=20)
    last_name = models.TextField(max_length=20)
    birth_date = models.DateField()
    phone = models.IntegerField()
    first_dose_date = models.DateField(blank=True, null=True)
    first_dose_done = models.BooleanField(default=False)
    second_dose_date = models.DateField(blank=True, null=True)
    second_dose_done = models.BooleanField(default=False)
    HOSPITAL_CHOICES = (
        (1, 'Dhaka Medical College Hospital'),
        (2, 'Delta Medical College'),
    )
    hospital_choice = models.PositiveSmallIntegerField(choices=HOSPITAL_CHOICES, blank=True, null=True)

    def __str__(self):
        return f"{self.nid} : {self.first_name}"


class Staff(models.Model):
    id = models.CharField(max_length=5, primary_key=True)
    user = models.OneToOneField(User, default=None, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.user.username


class Admin(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    objects = models.Manager()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            Admin.objects.create(user=instance)
        if instance.user_type == 2:
            Staff.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.admin.save()
    if instance.user_type == 2:
        instance.staff.save()

vaccine/forms.py
from django import forms
from .models import Member


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = (
            'nid',
            'first_name',
            'last_name',
            'birth_date',
            'phone',
        )


class VaccineRegister(forms.Form):
    nid = forms.IntegerField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    birth_date = forms.DateField()
    phone = forms.IntegerField()


class MemberUpdateForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = (
            'nid',
            'first_name',
            'last_name',
            'birth_date',
            'phone',
            'first_dose_date',
            'first_dose_done',
            'second_dose_date',
            'second_dose_done',
        )


class MemberUpdate(forms.Form):
    nid = forms.IntegerField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    birth_date = forms.DateField()
    phone = forms.IntegerField()
    first_dose_date = forms.DateField()
    first_dose_done = forms.BooleanField()
    second_dose_date = forms.DateField()
    second_dose_done = forms.BooleanField()

vaccine/views.py
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse

from .models import Member
from django.views import generic
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RegisterForm, MemberUpdateForm


class LandingPageView(generic.TemplateView):
    template_name = 'vaccine/vaccine.html'


class MemberListView(LoginRequiredMixin, generic.ListView):
    template_name = "vaccine/dashboard.html"
    queryset = Member.objects.all()
    context_object_name = 'members'


class FirstDoseView(LoginRequiredMixin, generic.ListView):
    template_name = "vaccine/dashboard.html"
    queryset = Member.objects.filter(first_dose_done='False')
    context_object_name = 'members'


class SecondDoseView(LoginRequiredMixin, generic.ListView):
    template_name = "vaccine/dashboard.html"
    queryset = Member.objects.filter(first_dose_done='True', second_dose_done='False')
    context_object_name = 'members'


class DoseDoneView(LoginRequiredMixin, generic.ListView):
    template_name = "vaccine/dashboard.html"
    queryset = Member.objects.members = Member.objects.filter(first_dose_done='True', second_dose_done='True')
    context_object_name = 'members'


class MemberDetailView(LoginRequiredMixin, generic.UpdateView):
    template_name = "vaccine/member_details.html"
    form_class = MemberUpdateForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        return Member.objects.filter()

    def get_success_url(self):
        return reverse("vaccine:dashboard")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this lead")
        return super(MemberDetailView, self).form_valid(form)


class MemberDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'vaccine/delete.html'
    queryset = Member.objects.all()

    def get_success_url(self):
        return reverse('vaccine:dashboard')


class HomePage(generic.CreateView):
    template_name = 'vaccine/vaccine.html'
    form_class = RegisterForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organisation
        return Member.objects.filter()

    def get_success_url(self):
        return reverse("vaccine:index")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully registered for vaccine.")
        return super(HomePage, self).form_valid(form)


class CheckDate(generic.TemplateView):
    template_name = "vaccine/checkdate.html"


class DateDetails(generic.DetailView):
    queryset = Member.objects.all()

    def get_queryset(self):
        user = self.request.user
        return Member.objects.filter()
    template_name = "vaccine/detailview.html"


class Verify(generic.DetailView):
    queryset = Member.objects.all()
    template_name = "vaccine/verify.html"



'''
def dashboard(request):
    members = Member.objects.all()
    context = {
        "members": members
    }
    return render(request, "vaccine/dashboard.html", context)


def member_details(request, pk):
    member = Member.objects.get(nid=pk)
    context = {
        "member": member
    }
    return render(request, "vaccine/member_details.html", context)


def first_dose(request):
    members = Member.objects.filter(first_dose_done='False')
    context = {
        "members": members
    }
    return render(request, "vaccine/first_dose.html", context)


def second_dose(request):
    members = Member.objects.filter(first_dose_done='True', second_dose_done='False')
    for member in members:
        if member.first_dose_done == "False" or member.second_dose_done == "True":
            members.delete()
    context = {
        "members": members
    }
    return render(request, "vaccine/second_dose.html", context)


def complete_dose(request):
    members = Member.objects.members = Member.objects.filter(first_dose_done='True', second_dose_done='True')
    context = {
        "members": members
    }
    return render(request, "vaccine/complete_dose.html", context)

'''

vaccine/templates/vaccine/checkdate.html
{% extends 'index.html' %}
{% block content %}

{% endblock %}

vaccine/templates/vaccine/complete_dose.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">All Doses Done</h1>
    </div>

    <section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto">
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">NID Number</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Phone</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First Dose</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Second Dose</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Update</th>

          </tr>
        </thead>
        <tbody>
        {% for member in members %}

            <tr>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.nid }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.first_name}} {{ member.last_name }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.phone}}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.first_dose_done }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.second_dose_done }}</td>

            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900"><a href="{% url 'vaccine:member-details' member.nid %}"><button class="ml-auto text-white bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-indigo-600 rounded">Update</button></a></td>

            </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock %}

vaccine/templates/vaccine/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">All Members</h1>
    </div>

    <section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto">
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">NID Number</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Phone</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First Dose</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Second Dose</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Update</th>

          </tr>
        </thead>
        <tbody>
        {% for member in members %}

            <tr>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.nid }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.first_name}} {{ member.last_name }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.phone}}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.first_dose_done }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.second_dose_done }}</td>

            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900"><a href="{% url 'vaccine:member-details' member.nid %}"><button class="ml-auto text-white bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-indigo-600 rounded">Update</button></a></td>

            </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock %}

vaccine/templates/vaccine/delete.html
{% extends 'base.html' %}
{% block content %}

<h2>Are you sure you want to delete this member?</h2>
<h1>{{ user.first_name }} {{ user.last_name }}</h1>
<form method="post">
    {% csrf_token %}
{{ form.as_p }}
<button type="submit">Delete</button>
</form>

{% endblock %}

vaccine/templates/vaccine/detailview.html
{% extends 'index.html' %}
{% block content %}
{{ member }}

{% endblock %}

vaccine/templates/vaccine/first_dose.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">First Dose Waiting List</h1>
    </div>

    <section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto">
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">NID Number</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Phone</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First Dose</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Second Dose</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Update</th>

          </tr>
        </thead>
        <tbody>
        {% for member in members %}

            <tr>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.nid }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.first_name}} {{ member.last_name }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.phone}}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.first_dose_done }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.second_dose_done }}</td>

            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900"><a href="{% url 'vaccine:member-details' member.nid %}"><button class="ml-auto text-white bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-indigo-600 rounded">Update</button></a></td>

            </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock %}

vaccine/templates/vaccine/member_details.html
{% extends 'base.html' %}
{% block content %}


<h1>{{ user.first_name }} {{ user.last_name }}</h1>
<form method="post">
    {% csrf_token %}
{{ form.as_p }}
<button type="submit">Update</button>
</form>

{% endblock %}

vaccine/templates/vaccine/second_dose.html
{% extends 'base.html' %}
{% block content %}
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Second Dose Waiting List</h1>
    </div>

    <section class="text-gray-600 body-font">
  <div class="container px-5 py-1 mx-auto">
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">NID Number</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Name</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Phone</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">First Dose</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Second Dose</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Update</th>

          </tr>
        </thead>
        <tbody>
        {% for member in members %}

            <tr>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.nid }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.first_name}} {{ member.last_name }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3">{{ member.phone}}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.first_dose_done }}</td>
            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900">{{ member.second_dose_done }}</td>

            <td class="border-t-2 border-gray-200 px-4 py-3 text-lg text-gray-900"><a href="{% url 'vaccine:member-details' member.nid %}"><button class="ml-auto text-white bg-gray-800 border-0 py-1 px-3 focus:outline-none hover:bg-indigo-600 rounded">Update</button></a></td>

            </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>
{% endblock %}

vaccine/templates/vaccine/vaccine.html
{% extends 'index.html' %}
{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
    <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
      <h1 class="title-font font-medium text-6xl text-gray-900">Sign up for Vaccine</h1>
      <p class="leading-relaxed mt-4 text-xl">Sign up as soon as possible for the Covid-19 vaccine to be safe.</p>
    </div>
    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
        <form method="post">
            {% csrf_token %}
      <h2 class="text-gray-900 text-lg font-medium title-font mb-5 text-center text-xl">Register for Vaccine</h2>
      <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">NID</label>
        <input type="number" name="nid" id="id_nid" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
        <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">First Name</label>
        <input type="text" id="id_first_name" name="first_name" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
        <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">Last Name</label>
        <input type="text" id="id_last_name" name="last_name"  class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
        <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">Date of Birth</label>
        <input type="text" name="birth_date" id="id_birth_date" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
        <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">Mobile Number</label>
        <input type="text" name="phone" id="id_phone" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <button type="submit" class="text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Register</button>
      <p class="text-xs text-gray-500 mt-3">Every Person is allowed to register only once.</p>
        </form>
    </div>
  </div>
</section>

{% endblock %}

vaccine/templates/vaccine/verify.html
{% extends 'index.html' %}
{% block content %}


{% endblock %}